
#pragma once

const char UDP_RESPONSE_TEMPLATE[] =
    "HTTP/1.1 200 OK\r\n"
    "CACHE-CONTROL: max-age=86400\r\n" // SSDP_INTERVAL
    "DATE: %1\r\n"
    "EXT:\r\n"
    "LOCATION: http://%2/setup.xml\r\n"
    "OPT: \"http://schemas.upnp.org/upnp/1/0/\"; ns=01\r\n"
    "01-NLS: %3\r\n"
    "SERVER: Unspecified, UPnP/1.0, Unspecified\r\n"
    "ST: %4\r\n"
    "USN: uuid:Socket-1_0-%3::%5\r\n"
    "X-User-Agent: redsonic\r\n"
    "\r\n";


const char HTTP_HEADER[] =
        "HTTP/1.1 200 OK\r\n"
        "CONTENT-LENGTH: %1\r\n"
        "CONTENT-TYPE: text/xml\r\n"
        "DATE: %2\r\n"
        "LAST-MODIFIED: Sat, 01 Jan 2000 00:01:15 GMT\r\n"
        "SERVER: Unspecified, UPnP/1.0, Unspecified\r\n"
        "X-User-Agent: Fauxmo\r\n"
        "CONNECTION: close\r\n\r\n";



const char SETUP_XML[] =
"<?xml version=\"1.0\" ?>"
"<root>"
    "<specVersion><major>1</major><minor>0</minor></specVersion>"
    "<device>"
        "<deviceType>urn:Belkin:device:controllee:1</deviceType>"
        "<friendlyName>%1</friendlyName>"
        "<manufacturer>Belkin International Inc.</manufacturer>"
        "<modelName>Emulated Socket</modelName>"
        "<modelNumber>3.1415</modelNumber>"
        "<UDN>uuid:Socket-1_0-%2</UDN>"
        "<serviceList>"
            "<service>"
                "<serviceType>urn:Belkin:service:basicevent:1</serviceType>"
                "<serviceId>urn:Belkin:serviceId:basicevent1</serviceId>"
                "<controlURL>/upnp/control/basicevent1</controlURL>"
                "<eventSubURL>/upnp/event/basicevent1</eventSubURL>"
                "<SCPDURL>/eventservice.xml</SCPDURL>"
            "</service>"
            "<service>"
                "<serviceType>urn:Belkin:service:metainfo:1</serviceType>"
                "<serviceId>urn:Belkin:serviceId:metainfo1</serviceId>"
                "<controlURL>/upnp/control/metainfo1</controlURL>"
                "<eventSubURL>/upnp/event/metainfo1</eventSubURL>"
                "<SCPDURL>/metainfoservice.xml</SCPDURL>"
            "</service>"
        "</serviceList>"
    "</device>"
"</root>";


const char METAINFO_XML[] =
"<scpd xmlns=\"urn:Belkin:service-1-0\">"
    "<specVersion>"
        "<major>1</major>"
        "<minor>0</minor>"
    "</specVersion>"
    "<actionList>"
        "<action>"
        "<name>GetMetaInfo</name>"
        "<argumentList>"
        "<retval />"
        "<name>GetMetaInfo</name>"
        "<relatedStateVariable>MetaInfo</relatedStateVariable>"
        "<direction>in</direction>"
        "</argumentList>"
        "</action>"
    "</actionList>"
    "<serviceStateTable>"
        "<stateVariable sendEvents=\"yes\">"
            "<name>MetaInfo</name>"
            "<dataType>string</dataType>"
            "<defaultValue>0</defaultValue>"
        "</stateVariable>"
    "</serviceStateTable>"
"</scpd>"
"\r\n\r\n";


const char EVENT_SERVICE_XML[] =
"<scpd xmlns=\"urn:Belkin:service-1-0\">"
    "<actionList>"
        "<action>"
            "<name>SetBinaryState</name>"
            "<argumentList>"
            "<argument>"
                "<retval/>"
                "<name>BinaryState</name>"
                "<relatedStateVariable>BinaryState</relatedStateVariable>"
                "<direction>in</direction>"
            "</argument>"
            "</argumentList>"
        "</action>"
        "<action>"
            "<name>GetBinaryState</name>"
            "<argumentList>"
                "<argument>"
                    "<retval/>"
                    "<name>BinaryState</name>"
                    "<relatedStateVariable>BinaryState</relatedStateVariable>"
                    "<direction>out</direction>"
                "</argument>"
            "</argumentList>"
        "</action>"
    "</actionList>"
    "<serviceStateTable>"
        "<stateVariable sendEvents=\"yes\">"
            "<name>BinaryState</name>"
            "<dataType>Boolean</dataType>"
            "<defaultValue>0</defaultValue>"
        "</stateVariable>"
        "<stateVariable sendEvents=\"yes\">"
            "<name>level</name>"
            "<dataType>string</dataType>"
            "<defaultValue>0</defaultValue>"
        "</stateVariable>"
    "</serviceStateTable>"
"</scpd>";


const char SOAP_RESPONSE[] =
"<s:Envelope "
    "xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\" "
    "s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">"
    "<s:Body>"
        "<u:%1%2Response "
            "xmlns:u=\"urn:Belkin:service:basicevent:1\">"
            "<%2>%3</%2>"
        "</u:%1%2Response>"
    "</s:Body>"
"</s:Envelope>";
